import { useRef, useState } from 'react';

function parseTraceText(text) {
  const parsed = JSON.parse(text);
  if (!parsed || !Array.isArray(parsed.traceEvents)) {
    throw new Error('Trace JSON must contain a traceEvents array.');
  }
  return parsed;
}

export default function TraceLoader({ onLoad, onError }) {
  const inputRef = useRef(null);
  const [dragActive, setDragActive] = useState(false);
  const [loading, setLoading] = useState(false);

  async function handleFile(file) {
    if (!file) {
      return;
    }

    try {
      setLoading(true);
      const text = await file.text();
      const payload = parseTraceText(text);
      onLoad(payload, file.name);
    } catch (error) {
      onError(error.message || 'Failed to parse trace file.');
    } finally {
      setLoading(false);
    }
  }

  async function loadFromServer() {
    try {
      setLoading(true);
      const response = await fetch('/trace.json', { cache: 'no-store' });
      if (!response.ok) {
        throw new Error('Unable to fetch /trace.json. Start `flux serve` with a trace path.');
      }
      const payload = parseTraceText(await response.text());
      onLoad(payload, '/trace.json');
    } catch (error) {
      onError(error.message || 'Failed to load trace from server.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="loader-stack">
      <div
        className={`dropzone ${dragActive ? 'is-active' : ''}`}
        onDragOver={(event) => {
          event.preventDefault();
          setDragActive(true);
        }}
        onDragLeave={() => setDragActive(false)}
        onDrop={(event) => {
          event.preventDefault();
          setDragActive(false);
          handleFile(event.dataTransfer.files?.[0]);
        }}
      >
        <p className="dropzone-title">Drop trace JSON here</p>
        <p className="dropzone-subtitle">
          Load a Chrome Trace Event file generated by the Flux CLI.
        </p>
        <div className="loader-actions">
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => inputRef.current?.click()}
            disabled={loading}
          >
            {loading ? 'Loading...' : 'Choose File'}
          </button>
          <button type="button" className="btn btn-ghost" onClick={loadFromServer} disabled={loading}>
            Load /trace.json
          </button>
        </div>
      </div>

      <input
        ref={inputRef}
        type="file"
        accept="application/json,.json"
        className="hidden-input"
        onChange={(event) => handleFile(event.target.files?.[0])}
      />
    </div>
  );
}
