import { useRef, useState } from 'react';

function parseTraceText(text) {
  const parsed = JSON.parse(text);
  if (!parsed || !Array.isArray(parsed.traceEvents)) {
    throw new Error('Trace JSON must contain a traceEvents array.');
  }
  return parsed;
}

export default function TraceLoader({ onLoad, onError }) {
  const inputRef = useRef(null);
  const [dragActive, setDragActive] = useState(false);
  const [loading, setLoading] = useState(false);

  async function handleFile(file) {
    if (!file) return;
    try {
      setLoading(true);
      const payload = parseTraceText(await file.text());
      onLoad(payload, file.name);
    } catch (err) {
      onError(err.message || 'Failed to parse trace file.');
    } finally {
      setLoading(false);
    }
  }

  async function loadFromServer() {
    try {
      setLoading(true);
      const response = await fetch('/trace.json', { cache: 'no-store' });
      if (!response.ok) throw new Error('Could not fetch /trace.json — run `flux serve --trace trace.json` first.');
      const payload = parseTraceText(await response.text());
      onLoad(payload, '/trace.json');
    } catch (err) {
      onError(err.message || 'Failed to load trace from server.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="loader-panel">
      <div
        className={`dropzone ${dragActive ? 'is-active' : ''}`}
        onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
        onDragLeave={() => setDragActive(false)}
        onDrop={(e) => { e.preventDefault(); setDragActive(false); handleFile(e.dataTransfer.files?.[0]); }}
      >
        <div className="dropzone-icon">📂</div>
        <p className="dropzone-title">Drop your trace file here</p>
        <p className="dropzone-subtitle">Accepts Chrome Trace JSON files generated by Flux</p>
        <div className="loader-actions">
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => inputRef.current?.click()}
            disabled={loading}
          >
            {loading ? 'Loading…' : 'Choose File'}
          </button>
          <button type="button" className="btn btn-ghost" onClick={loadFromServer} disabled={loading}>
            Load from Server
          </button>
        </div>
      </div>

      <div className="loader-divider">how to generate a trace</div>

      <div className="loader-steps">
        <div className="loader-step">
          <div className="step-num">1</div>
          <div className="step-text">
            Profile your model: <code>flux profile --script your_model.py --output trace.json</code>
          </div>
        </div>
        <div className="loader-step">
          <div className="step-num">2</div>
          <div className="step-text">
            Serve it locally: <code>flux serve --trace trace.json</code> — then click "Load from Server"
          </div>
        </div>
        <div className="loader-step">
          <div className="step-num">3</div>
          <div className="step-text">
            Or drag and drop the <code>trace.json</code> file directly onto this window
          </div>
        </div>
      </div>

      <input
        ref={inputRef}
        type="file"
        accept="application/json,.json"
        className="hidden-input"
        onChange={(e) => handleFile(e.target.files?.[0])}
      />
    </div>
  );
}
